server:
  port: 9090
spring:
  application:
    name: apihub_gateway
dubbo:
  application:
    name: dubbo
    qosEnableL: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
